#macro( strip $className $_nameOfScript)
#if($className.startsWith("Eval"))$className.substring(4)#else$_nameOfScript.substring(0,1).toUpperCase()$_nameOfScript.substring(1)#end
#end
#set( $nameOfScriptInCamelCase = "#strip( $classNameOfScript, $_nameOfScript )" )
site_name: Siddhi Script ${nameOfScriptInCamelCase}
site_description: Siddhi Script ${nameOfScriptInCamelCase} Extension
repo_name: Siddhi-Script-${nameOfScriptInCamelCase}
repo_url:
edit_url:
copyright:
theme:
  name: 'material'
  logo: images/siddhi-logo.svg
  favicon: images/favicon.ico
  palette:
    primary: teal
    accent: teal
extra_css:
  - assets/stylesheets/extra.css
extra_javascript:
  - assets/javascripts/extra.js
extra:
  social:
google_analytics:
markdown_extensions:
  - markdown.extensions.admonition
pages:
  - Information : index.md
  - API Docs:
      - latest: api/latest.md
  - License: license.md

