#macro( strip $className $_mapType)
#set ($stringLength = $className.length() - 4)
#if($className.endsWith("Sink"))$className.substring(0, $stringLength)#else$_mapType.substring(0,1).toUpperCase()$_mapType.substring(1)#end
#end
#set( $typeOfmapinCamelCase = "#strip( $classNameOfSink, $_mapType )" )
site_name: Siddhi Map ${typeOfmapinCamelCase}
site_description: Siddhi Map ${typeOfmapinCamelCase} Extension
repo_name: Siddhi-Store-${typeOfmapinCamelCase}
repo_url:
edit_url:
copyright:
theme:
  name: 'material'
  logo: images/siddhi-logo.svg
  favicon: images/favicon.ico
  palette:
    primary: teal
    accent: teal
extra_css:
  - assets/stylesheets/extra.css
extra_javascript:
  - assets/javascripts/extra.js
extra:
  social:
google_analytics:
markdown_extensions:
  - markdown.extensions.admonition
pages:
  - Information : index.md
  - API Docs:
      - latest: api/latest.md
  - License: license.md